### ISSUE TITLE
Marker Cluster not showing

### ISSUE THREAD

**Issue by enekobyhours** [nuxt-modules/leaflet#75]
Hi,

I have started a new Nuxt project (version 3.12.4) using the code provided in the [Nuxt Leaflet Marker Cluster documentation](https://leaflet.nuxtjs.org/guide/marker-cluster.html). However, the markers are not displaying as expected.

I have configured the project with ssr: false, but the issue persists.

Am I missing something in the setup? Any help would be appreciated. Thanks!

![image](https://github.com/user-attachments/assets/8533ac36-a3f8-413d-aa88-73521fd74cab)

**Comment by Gugustinette** [comment]
Hi !

Any error in your browser console or server logs ?

**Comment by enekobyhours** [comment]
Yes, sorry.

I am getting this error: `Uncaught (in promise) TypeError: MarkerClusterGroup is not a constructor` wich comes from the line `const markerCluster = new MarkerClusterGroup();` in _useLMarkerCluster.js_ file.

**Comment by Gugustinette** [comment]
That's weird, I would expect such error to happen if you didn't activate the plugin or so.

Can you provide a reproduction ?

**Comment by enekobyhours** [comment]
https://stackblitz.com/edit/github-ab7plw?file=app.vue

**Comment by Gugustinette** [comment]
Well I think I found a temporary fix that specify the import of `leaflet.markercluster` before calling the composable :

```typescript

// When the map is ready
const onMapReady = async () => {

  // Temp fix
  await import('leaflet.markercluster')

  useLMarkerCluster({
    leafletObject: map.value.leafletObject,
    markers: locations,
  });
};
```

But still, I don't know where the error come from. 😕

**Comment by tratteo** [comment]
Just following up here. I am having a similar problem, I am getting this error:
![image](https://github.com/user-attachments/assets/60470726-fcfb-4fb8-a983-cd8fb2ee8bff)

I have tried to include the manual import of the `leaflet.markercluster` as follows but the problem is persisting:
```ts
        // Added this
        await import('leaflet.markercluster')
        const res = await useLMarkerCluster({
            leafletObject: mapEl.value!.leafletObject,
            markers: props.clusteredMarkers.map((m) => ({
                name: m.id,
                lat: m.coords[0],
                lng: m.coords[1],
                popup: m.popup,
            })),
        });
```

**Comment by Gugustinette** [comment]
Yeah I remember getting this kind of production-only error, and I must say I don't know what the fuck is going on lol

I spent hours trying to debug why is this behaving so weirdly, that seems like a combination of :
- Leaflet being an old browser library, which has plugins that expects `L` to be loaded as a global variable to extend its features.
  - Which makes writing Nuxt Leaflet very hard (even though the code is pretty light and straight forward)
- Weird build-time behavior with Nitro or Rollup or esbuild,...

I'm clearly laking some expertise here, and I must say the error is very hard to reproduce, it seems sometimes the browser will cache `L`, sometimes not,... The error itself is unstable 😭

**Comment by tratteo** [comment]
Yeah I am seeing that the error is not easily reproducible. I can do some tests by deleting cache and stuff, and checking in which situation it presents again. 
**However, at the moment it is giving me the error 100% of the time.**
Is there something I can help with?
Is there a way to force the global loading of the L variable?

I really wanna help, also because I am building a product with map functionalities. 
Let me know if I can help in any way!

**Comment by Gugustinette** [comment]
Well It would be great to provide a [Stackblitz](https://stackblitz.com/) reproduction.

**Comment by Gugustinette** [comment]
Well I just tested it and got this error in development mode 😭

![Capture d’écran 2024-09-12 à 17 57 17](https://github.com/user-attachments/assets/014e29aa-6cc9-46a0-a7a5-97d4c4a3c309)

**Comment by tratteo** [comment]
Yep, I was writing about that too but I saw that that error is indeed random, hence it happens sometimes, really do not know in which situations...
However the error in production happens always

**Comment by Gugustinette** [comment]
No significative update as far as I know, and I encountered these behavior even at the beginning of developing `@nuxtjs/leaflet`.

We would probably need the help of a more experienced person here.

**Comment by tratteo** [comment]
I did some testing with the app I am building and I can confirm the problem seems strictly related to the `leaflet.markercluster` package. Displaying markers without clusterization seems to work perfectly in every situation, never had a problem.

However, I was not able to exactly understand where the problem is with the package 🫠

**Comment by tratteo** [comment]
## Update
Upon upgrading `@nuxtjs/leaflet` to `^1.2.3`, I am getting the following error (even with clustering disabled) and I am not able to resolve it in any way, at the moment all map functionalities are not working:
![image](https://github.com/user-attachments/assets/541dabea-59dd-47e4-ba5c-08103fde890d)

**Comment by Gugustinette** [comment]
@tratteo Well that is probably related to this issue : https://github.com/nuxt-modules/leaflet/issues/80 which is unfixable at the moment.

**Comment by satriaenur** [comment]
@Gugustinette , I've seen #80 has been resolved, do we need to update things for markercluster supports to be working?
I still getting
```
TypeError: MarkerClusterGroup is not a constructor
    at useLMarkerCluster (useLMarkerCluster.js?v=1cc1ed8d:4:25)
```

**Comment by Gugustinette** [comment]
@satriaenur Unfortunately not, these 2 issues are not related 😕

Marker Cluster support is still unstable on last version, and I still don't know where it comes from 😭

**Comment by joe-irving** [comment]
In a slightly strange turn of events. I found something that "fixes" it. But y'all are going to hate it.

Assuming at the start of your component you have

```ts
import * as L from "leaflet";
```

Then during the creation of marker clusters add a `console.log` for `L`:

```ts
async function mapReady() {
  if (!map.value) {
    return;
  }
  //   If you include `import * as L from "leaflet";` at the top of this file, and put `console.log(L);`,
  // then in production the marker clustering works. If you remove this, it still works in development
  // but when you run it in production it fails and shows no markers as the Leaflet global L doesn't appear
  // to have registered
  // However, this may throw errors while in development if referenced (you can surround it by conditionals based on
  // !import.meta.dev and it doesn't make a difference). So the only option I see is commenting and uncommenting

  console.log(L);
  // @ts-ignore This is a temp fix see https://github.com/nuxt-modules/leaflet/issues/75#issuecomment-2326991133
  await import("leaflet.markercluster");
  useLMarkerCluster({
    leafletObject: map.value.leafletObject,
    markers: markersList.value,
  });
}
```

This means it works in production for me, however it does not work in development. When I use `yarn dev` I get this output:

```
[Vue Router warn]: uncaught error during route navigation:
ReferenceError: window is not defined
    at <anonymous> (//PATH//node_modules/leaflet/src/core/Util.js:217:24)
    at //PATH//node_modules/leaflet/dist/leaflet-src.js:7:66
    at Object.<anonymous> (//PATH//node_modules/leaflet/dist/leaflet-src.js:10:3)
    at Module._compile (node:internal/modules/cjs/loader:1267:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1321:10)
    at Module.load (node:internal/modules/cjs/loader:1125:32)
    at Module._load (node:internal/modules/cjs/loader:965:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:165:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:192:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

suggesting it is trying to access `window` server side.

So, yeah I got this working by having to comment and un-comment a line each time i release it

**Comment by Gugustinette** [comment]
bro wtf 😭

Maybe having a reference to `L` (through `console.log(L)` in this case) before the import changes `L`'s scope or something.
That's an interesting path to investigate, thanks @joe-irving !

**Comment by miladmeidanshahi** [comment]
still same issue we have to import it manually.

**Comment by tratteo** [comment]
For anybody still having problems with this I fixed it by using leaflet native, without using the nuxt module. Requires a little bit more setup but works perfectly.

**Comment by thorge** [comment]
> Well I think I found a temporary fix that specify the import of `leaflet.markercluster` before calling the composable :
> 
> // When the map is ready
> const onMapReady = async () => {
> 
>   // Temp fix
>   await import('leaflet.markercluster')
> 
>   useLMarkerCluster({
>     leafletObject: map.value.leafletObject,
>     markers: locations,
>   });
> };
> 
> But still, I don't know where the error come from. 😕

This fix can be used as a workaround, using leaflet native is also an option. But I would prefer to have this extension fixed. Anyone working on this?
